version: '3.8'
services:
  nginx:
    build: ./client
    ports:
      - "8070:8080"
    depends_on:
      - app
    
  app:
    build: ./server
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - NODE_PORT=9090
      - ADMIN_CODE
    expose:
      - 9090
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.8
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  # admin:
  #   image: mongo-express
  #   ports:
  #     - 8071:8081
  #   depends_on:
  #     - mongo
    
volumes:
  mongodb: