version: '3.8'
services:
  nginx:
    build: ./client
    ports:
      - "8070:8080"
    depends_on:
      - app
    restart: always
    
  app:
    build: ./server
    environment:
      - NODE_PORT=9090
      - ADMIN_CODE
    expose:
      - 9090
    restart: always
