version: '3.8'
services:
  nginx:
    build: ./client
    volumes:
      - ./client/src:/var/www/html
  
  app:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "9229:9229"
    command: npm run debug

  admin:
    image: mongo-express
    ports:
      - 8071:8081
    depends_on:
      - mongo

volumes:
  node_modules: