version: "3"

services:
  minecraft:
    image: itzg/minecraft-server:java11
    container_name: minecraft
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 25565:25565

    environment:
      - EULA=TRUE
      - ENABLE_AUTOPAUSE=TRUE
      - MAX_TICK_TIME=-1
      - VERSION=1.16.5
      - TYPE=FORGE
      - OPS=NatsuGame

    volumes:
      - /mnt/disk/minecraft-server:/data