version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - 25565:25565

    environment:
      - EULA=TRUE
      - ENABLE_AUTOPAUSE=TRUE
      - MAX_TICK_TIME=-1

    # volumes:
    #   - /srv/volumes/minecraft_server:/data