version: '3'
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: bridge

    volumes:
      - /mnt/disk/plex/config:/config
      - /mnt/disk/library:/data
    environment:
      - VERSION=docker
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - PLEX_CLAIM # only needed at first start, can be injected through .env

    ports:
      # Full port listing is available from the Plex website:
      # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/

      - "32400:32400" # (for access to the Plex Media Server) [required]
      - "32410:32410/udp" # (for current GDM network discovery)
      - "32412:32412/udp" # (for current GDM network discovery)
      - "32413:32413/udp" # (for current GDM network discovery)
      - "32414:32414/udp" # (for current GDM network discovery)
      - "32469:32469" # (for access to the Plex DLNA Server)
